// Maps department names to their API endpoint identifiers
export const DEPARTMENT_TO_ENDPOINT: Record<string, string> = {
  "Aging": "aging",
  "Animal Services": "animalServices",
  "Building and Safety": "buildingAndSafety",
  "Cannabis Regulation": "cannabisRegulation",
  "City Administrative Officer": "cityAdministrativeOfficer",
  "City Attorney": "cityAttorney",
  "City Clerk": "cityClerk",
  "City Ethics Commission": "cityEthicsCommission",
  "City Planning": "cityPlanning",
  "Civil Human Rights": "civilHumanRights",
  "Civil, Human Rights, and Equity": "civilHumanRights",
  "Community Investment Families": "communityInvestmentFamilies",
  "Community Investment for Families": "communityInvestmentFamilies",
  "Controller": "controller",
  "Council": "council",
  "Cultural Affairs": "culturalAffairs",
  "Disability": "disability",
  "Economic and Workforce": "economicAndWorkforce",
  "Economic and Workforce Development": "economicAndWorkforce",
  "El Pueblo": "elPueblo",
  "Emergency Management": "emergencyManagement",
  "Employee Relations": "employeeRelations",
  "Employee Relations Board": "employeeRelations",
  "Fire": "fire",
  "General Services": "generalServices",
  "Information Technology": "informationTechnology",
  "Information Technology Agency": "informationTechnology",
  "Los Angeles City Tourism": "losAngelesCityTourism",
  "Los Angeles Housing": "losAngelesHousing",
  "Mayor": "mayor",
  "Neighborhood Empowerment": "neighborhoodEmpowerment",
  "Capital Finance Administration": "nonDepartCapitalFinance",
  "Capital Improvement Expense": "nonDepartCapitalImprovement",
  "General": "nonDepartGeneral",
  "General City Purposes": "nonDepartGeneralCityPurpose",
  "Human Resources Benefits": "nonDepartHumanResources",
  "Leasing": "nonDepartLeasing",
  "Liability Claims": "nonDepartLiabilityClaims",
  "Petroleum Products": "nonDepartPetroleum",
  "Unappropriated Balance": "nonDepartUnappropriated",
  "Water and Electricity": "nonDepartWaterAndElectric",
  "Office of Finance": "officeOfFinance",
  "Personnel": "personnel",
  "Police": "police",
  "Public Accountability": "publicAccountability",
  "Public Works - Board of Public": "publicWorksBoardOfPublic",
  "Board of Public Works": "publicWorksBoardOfPublic",
  "Public Works - Contract Admin": "publicWorksContractAdmin",
  "Contract Administration": "publicWorksContractAdmin",
  "Public Works - Engineering": "publicWorksEngineering",
  "Engineering": "publicWorksEngineering",
  "Public Works - Sanitation": "publcWorksSanitation",
  "Sanitation": "publcWorksSanitation",
  "Public Works - Street Lighting": "publicWorksStreetLighting",
  "Street Lighting": "publicWorksStreetLighting",
  "Public Works - Street Services": "publicWorksStreetServices",
  "Street Services": "publicWorksStreetServices",
  "Transportation": "transportation",
  "Youth Development": "youthDevelopment",
  "Zoo": "zoo",
};

export const getEndpointForDepartment = (department: string): string | null => {
  return DEPARTMENT_TO_ENDPOINT[department] || null;
};
